'use client';

import { useEffect, useRef, useState } from 'react';
import { CheckCircle2, Download, ShieldCheck, Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle } from '@/components/ui/card';
import { SUPPORTED_CURRENCIES } from '@/lib/money';

type User = { name: string; email: string; baseCurrency: string; timezone: string; theme: string };

export default function SettingsPage() {
  const [user, setUser] = useState<User | null>(null); const [status, setStatus] = useState<{ kind: 'success' | 'error'; text: string } | null>(null); const fileInput = useRef<HTMLInputElement>(null);
  useEffect(() => { fetch('/api/auth/me').then((response) => response.json()).then((result) => { if (result.success) setUser(result.data); }).catch(() => setStatus({ kind: 'error', text: 'We could not load your profile.' })); }, []);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!user) return; setStatus(null); const response = await fetch('/api/preferences', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(user) }); const result = await response.json(); if (!response.ok) { setStatus({ kind: 'error', text: result.error ?? 'Unable to save your preferences.' }); return; } setUser(result.data); setStatus({ kind: 'success', text: 'Preferences saved.' }); }
  async function download() { setStatus(null); try { const response = await fetch('/api/backup'); if (!response.ok) throw new Error(); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `expense-tracker-backup-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); setStatus({ kind: 'success', text: 'Your private JSON backup has been downloaded.' }); } catch { setStatus({ kind: 'error', text: 'Unable to create a backup. Please try again.' }); } }
  async function restore(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setStatus(null); try { if (file.size > 10_000_000) throw new Error('This file is too large.'); const data = JSON.parse(await file.text()); const response = await fetch('/api/backup', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type: 'RESTORE_JSON', data }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? 'Unable to restore the backup.'); setStatus({ kind: 'success', text: `Restored ${result.data.imported} transaction${result.data.imported === 1 ? '' : 's'}; skipped ${result.data.skipped} duplicate${result.data.skipped === 1 ? '' : 's'}.` }); window.dispatchEvent(new Event('transaction-updated')); } catch (error) { setStatus({ kind: 'error', text: error instanceof Error ? error.message : 'Choose a valid Expense Tracker backup.' }); } finally { event.target.value = ''; } }
  if (!user) return <div className="py-16 text-center text-sm text-neutral-500 dark:text-neutral-400">Loading your preferences…</div>;
  return <div className="max-w-3xl space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--accent)]">Personal space</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-neutral-900 dark:text-neutral-100">Settings & data</h1><p className="mt-2 text-sm text-neutral-500 dark:text-neutral-400">Control how your private workspace is presented and backed up.</p></header>
    {status && <div role="status" className={`flex items-center gap-2 rounded-xl px-4 py-3 text-sm ${status.kind === 'success' ? 'bg-[var(--income-bg)] text-[var(--income)]' : 'bg-[var(--danger-bg)] text-[var(--danger)]'}`}><CheckCircle2 className="h-4 w-4" />{status.text}</div>}
    <Card><CardHeader><CardTitle>Profile & base currency</CardTitle></CardHeader><form className="space-y-4" onSubmit={save}><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Name<input className="mt-1.5 w-full rounded-xl border border-neutral-200 bg-white px-3 py-2.5 outline-none focus:border-[var(--accent)] dark:border-neutral-800 dark:bg-neutral-900" value={user.name} onChange={(event) => setUser({ ...user, name: event.target.value })} required /></label><label className="block text-sm font-medium">Email<input className="mt-1.5 w-full cursor-not-allowed rounded-xl border border-neutral-200 bg-neutral-50 px-3 py-2.5 text-neutral-500 dark:border-neutral-800 dark:bg-neutral-900" value={user.email} disabled /></label></div><label className="block max-w-sm text-sm font-medium">Base currency<select className="mt-1.5 w-full rounded-xl border border-neutral-200 bg-white px-3 py-2.5 outline-none focus:border-[var(--accent)] dark:border-neutral-800 dark:bg-neutral-900" value={user.baseCurrency} onChange={(event) => setUser({ ...user, baseCurrency: event.target.value })}>{Object.values(SUPPORTED_CURRENCIES).map((currency) => <option key={currency.code} value={currency.code}>{currency.code} — {currency.name}</option>)}</select><span className="mt-1.5 block text-xs font-normal leading-5 text-neutral-500 dark:text-neutral-400">Choose this before adding accounts. Existing accounts stay in their current currency to keep historical totals accurate.</span></label><Button type="submit">Save preferences</Button></form></Card>
    <Card><CardHeader><CardTitle>Private backup</CardTitle></CardHeader><p className="text-sm leading-6 text-neutral-500 dark:text-neutral-400">Export a portable snapshot of your accounts, categories, transactions, budgets, and recurring payments. Backup files contain financial information—store them somewhere you trust.</p><div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" onClick={download}><Download className="h-4 w-4" /> Download JSON backup</Button><input ref={fileInput} className="sr-only" accept="application/json,.json" type="file" onChange={restore} /><Button variant="outline" onClick={() => fileInput.current?.click()}><Upload className="h-4 w-4" /> Restore a backup</Button></div></Card>
    <Card className="border-[var(--border-subtle)] bg-[var(--warm-surface)]"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[var(--income)]" /><div><h2 className="text-sm font-semibold">How your data is protected</h2><p className="mt-1 text-sm leading-6 text-neutral-600 dark:text-neutral-300">Your data is isolated by your signed-in account. Sessions are HTTP-only, input is validated on the server, and financial values are stored as integer minor units—not floats.</p></div></div></Card>
  </div>;
}
